## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/
## timezone: https://github.com/moment/moment-timezone/blob/develop/data/packed/latest.json

# Site
title: cyd’s blog
author: cyd
#subtitle: 程序猿
language: zh-CN
timezone: Asia/Shanghai
description: Unity、iOS、Cocos

# URL
url: https://cdcyd.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
tag_dir: tags
code_dir: downloads/code
i18n_dir: :lang
source_dir: source
public_dir: public
archive_dir: archives
category_dir: categories
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
# Hexo uses Moment.js to parse and display date
# You can customize the date format as defined in
# http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
# per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Extensions
theme: next
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true

# Deployment
# Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:cdcyd/cdcyd.github.io.git
branch: master
